server:
  port: 8092

spring:
  application:
    name: QUESTION-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/question_service
    username: root
    password: Hridayesh1@
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
    prefer-ip-address: true